label/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 


urlpatterns = [
    path('photo/', include('photo.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^update/(?P<id>\d+)/$', views.update, name='update'),
    path('update_1/', views.update_1, name='update_1'),
]

photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField


class Photos(models.Model):
    id = models.IntegerField(primary_key=True)
    img = models.ImageField(null=True, blank=True, upload_to='media')
    using_count = models.IntegerField(default=0)
    gender = models.CharField(max_length=20)
    quality = models.CharField(max_length=10)
    type = models.IntegerField(default=0)
    
    answer1 = models.IntegerField(default=0)
    answer2 = models.IntegerField(default=0)
    answer3 = models.IntegerField(default=0)

class Counter(models.Model):
    id = models.IntegerField(primary_key=True)
    count = models.IntegerField(default=0)
    ids = ArrayField(models.IntegerField(), size=24,)
    ans1 = ArrayField(models.IntegerField(), size=24,)
    ans2 = ArrayField(models.IntegerField(), size=24,)
    ans3 = ArrayField(models.IntegerField(), size=24,)

photo/forms.py
from django import forms
from .models import Photos

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Photos
        fields = [
            'answer1',
            'answer2',
            'answer3',
        ]

photo/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Photos, Counter
from .forms import UpdateForm
from django.contrib import messages
import random
from django.urls import reverse

#import logging
#stdlogger = logging.getLogger(__name__)
#dbalogger = logging.getLogger('dba')


types = (1,2)
gender = ('Bedroom', 'Livingroom', 'Bathroom', 'Kitchen')
quality = ('kotu', 'orta', 'iyi')

max_survey_image_count = 30
image_count = 30#24
def_ans = [-1]*image_count
max_using_count = 10


def update(request, id):
    print("Entering debug msg", id, request)
    #stdlogger.debug("Entering update/id method")


    survey = get_object_or_404(Counter, id=id)

    photo = get_object_or_404(Photos, id=survey.ids[survey.count])
    form = UpdateForm(request.POST or None, request.FILES or None, instance=photo)
    print(form.is_valid())
    
    #print(photo.answer1)

    if form.is_valid():
        survey.ans1[survey.count] = photo.answer1
        survey.ans2[survey.count] = photo.answer2
        survey.ans3[survey.count] = photo.answer3
        survey.count = survey.count + 1 

        form.save()
        photo.save()
        survey.save()

        #return HttpResponseRedirect("/photo/update/{}".format(id))

    if survey.count == max_survey_image_count:
        context = {'survey': survey}
        return render(request, 'photo/finish.html', context=context)

    photo = get_object_or_404(Photos, id=survey.ids[survey.count])
    context = {'form' : form, 'photo': photo, 'survey': survey}
    print("Rendered template with:", context)

    return render(request, 'photo/template.html', context=context)

def update_1(request):
    for i in range(0, max_survey_image_count):
        surveys = Counter.objects.filter(count=i)
        if len(surveys) == 0:
            continue
        break
        
    if len(surveys) > 0:
        rand_int = random.randint(0, len(surveys)-1)
        surveys[rand_int].count = 0
        surveys[rand_int].save()
        return HttpResponseRedirect("/photo/update/{}".format(surveys[rand_int].id))

    """
    else:

        all_counters = Counter.objects.all()
        if len(all_counters) <= 0:
            print("Populating DB from scratch.")

            i = 1
            total_image_in_db = len(Photos.objects.all())

            for photo in Photos.objects.all():
                photo.using_count = 0
                photo.save

            while True:
                if len(Photos.objects.filter(using_count=max_using_count)) >= (total_image_in_db - image_count - 1): break
                
                print(f"\r Creating new Counter object {i}", end="")
                new_ct = Counter(id=i, ids=[], ans1=def_ans, ans2=def_ans, ans3=def_ans)
                i = i + 1

                for e in gender:
                    for f in quality:
                        for c in types:
                            if e == "Livingroom":
                                for i in range(2):
                                    photos = Photos.objects.filter(gender=e, quality=f, type=c)
                                    while True:
                                        photo = photos[random.randint(0, len(photos)-1)]
                                        if photo.id not in new_ct.ids and photo.using_count < max_using_count*2:
                                            break
                                    photo.using_count = photo.using_count + 1
                                    photo.save()
                                    new_ct.ids.append(photo.id)
                            else:
                                photos = Photos.objects.filter(gender=e, quality=f, type=c)
                                while True:
                                    photo = photos[random.randint(0, len(photos)-1)]
                                    if photo.id not in new_ct.ids and photo.using_count < max_using_count:
                                        break
                                photo.using_count = photo.using_count + 1
                                photo.save()
                                new_ct.ids.append(photo.id)

                new_ct.save()
                print(f"\r Finished Creating new Counter object {i}", end="")

        print("Finished Script-2")      
        return HttpResponseRedirect("/photo/update_1/")
        """

    return render(request, 'photo/no_survey.html')
    



"""
python manage.py shell -c "from photo.models import Counter; print(len(Counter.objects.all()))"
python manage.py shell -c "from photo.models import Photos; print(len(Photos.objects.all()))"

python manage.py shell -c "from photo.models import Counter; Counter.objects.all().delete()"

python manage.py flush
python manage.py shell -c "import Script_1"
python manage.py shell -c "import Script_2"

python manage.py runserver 

"""

photo/templates/photo/finish.html
{% load static %}
<html>
  <head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>label me</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
    <script type="text/javascript">  
      function cyrb53(str, seed = 0) {
          let h1 = 0xdeadbeef ^ seed, h2 = 0x41c6ce57 ^ seed;
          for (let i = 0, ch; i < str.length; i++) {
              ch = str.charCodeAt(i);
              h1 = Math.imul(h1 ^ ch, 2654435761);
              h2 = Math.imul(h2 ^ ch, 1597334677);
          }
          h1 = Math.imul(h1 ^ (h1>>>16), 2246822507) ^ Math.imul(h2 ^ (h2>>>13), 3266489909);
          h2 = Math.imul(h2 ^ (h2>>>16), 2246822507) ^ Math.imul(h1 ^ (h1>>>13), 3266489909);
          return 4294967296 * (2097151 & h2) + (h1>>>0);
      };
    </script>
  </head>
  <style>

  *{
    box-sizing:border-box;
    padding:0;
    margin:0;
    font-family: Arial, Helvetica, sans-serif;
  }
  

  .questions {
      background-repeat: no-repeat; 
      background-size: auto; 
      border: 3px solid #010801; 
      border-radius: 3px; 
      box-shadow: 0 0 2px 1px #9a9182;
      background-color: #0071b9;
      background-repeat: repeat; 
      background-attachment: scroll;
      background-clip: border-box;
      background-size: cover;
      object-fit:contain;
      max-width: 85%;
      margin-left: 7.5%;
      margin-top: 3%;
      margin-bottom: 5%;
      padding-bottom: 2vmin;
      text-align:center;
      color: whitesmoke;
      padding: 25px;
    }
    .questions p {
      font-size: 2vmax;
      margin-top: 1%;
    }

    .container-fluid {
      width:100%;
      border:2px solid black;
      display:grid;
      height:100%;
    }
    .left {
      display:flex;
      flex-direction:column;
      background-color: #cde3f1;
      background-clip: border-box;
      background-size: 100% 100%;
      text-align: center; 
      justify-content:flex-start;
      padding-top: 3vh;
    }

  </style>

  <body >

    <div class="container-fluid" >
        <div class="left" >
          
          <div style="overflow-x:auto;margin-bottom:2%;" class="questions">
              <h1>Tebrikler Anketin Sonuna Geldiniz. Yardımlarınız İçin Teşekkür Ederiz.
              </h1>
              <br>
              <h2>adesso Turkey ArGe Departmanı</h2>
          </div>
          
          <h1> Çekilişe katılmak için aşağıda bulunan tek kullanımlık kodu en alttaki form içine yapıştırarak gönderiniz.</h1><br>
          <div style="overflow-x:auto;margin-top:1%;margin-bottom:1%;" class="questions">
            <h2 id="demo">
            {{survey.id}} 
            </h2>

            <script>
              document.getElementById("demo").innerHTML = cyrb53("adesso_"+{{survey.id}});
            </script>

            <input hidden id="summary_text" type="text" value="error:{{survey.id}}" >

            <script>
              document.getElementById("summary_text").value = cyrb53("adesso_"+{{survey.id}});
            </script>

            <button style="overflow-x:auto;margin-top:1%;margin-bottom:1%;padding:5px" onclick="
              var copyText = document.getElementById('summary_text');
              copyText.hidden=false;
              copyText.select();copyText.setSelectionRange(0, 99999);
              document.execCommand('copy');
              copyText.hidden=true;">
                Kopyala
              </button>  
          </div>    

          <div style="overflow-x:auto; margin-top:1px" class="questions">
              <iframe width="640px" height= "480px" src= "https://forms.office.com/Pages/ResponsePage.aspx?id=ZVc1PdlnzUecer8xF59W63uOUYArvrhKrbdMpgsBpIdUNlQ3SEhEUjAwQjFTRzdFQkpKNkpSQ1UwTy4u&embed=true" frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>
          </div>


        </div>
        
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}">
      
      

      function myFunction() {
        /* Get the text field */
        var copyText = document.getElementById("summary_text");
        /* Select the text field */
        copyText.hidden=false;
        copyText.select();
        copyText.setSelectionRange(0, 99999); /* For mobile devices */
        /* Copy the text inside the text field */
        document.execCommand("copy");
        /* Alert the copied text */
        alert("Copied the text: " + copyText.value);
      } 
    </script>
  
  </body>
</html>

photo/templates/photo/no_survey.html
{% load static %}
<html>
  <head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>label me</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
  </head>
  <style>

  *{
    box-sizing:border-box;
    padding:0;
    margin:0;
  }
  

    .questions {
      background-repeat: no-repeat; 
      background-size: auto; 
      border: 3px solid #010801; 
      border-radius: 3px; 
      box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
      background-color: cadetblue;
      background-repeat: repeat; 
      background-attachment: scroll;
      background-clip: border-box;
      background-size: cover;
      object-fit:contain;
      max-width: 85%;
      margin-left: 7.5%;
      margin-top: 3%;
      margin-bottom: 5%;
      padding-bottom: 2vmin;
      text-align:center;
      color: whitesmoke;
    }
    .questions p {
      font-size: 2vmax;
      margin-top: 1%;
    }

    .container-fluid {
      width:100%;
      border:2px solid black;
      display:grid;
      height:100%;
    }
    .left {
      display:flex;
      flex-direction:column;
      background-color: darkgray;
      background-clip: border-box;
      background-size: 100% 100%;
      text-align: center; 
      justify-content:flex-start;
      padding-top: 3vh;
    }


  </style>

  <body >
    <div class="container-fluid" >
        <div class="left" >
          
          <div style="overflow-x:auto;" class="questions">
              <h1>Şu anda yapılacak bir anket bulunmamaktadır. Teşekkür Ederiz.
                  (Sayfayı Kapatabilirsiniz.)
              </h1><br>
              <h1>adesso Turkey</h1>
          </div>
        </div>      
    </div>
  
  <script src="{% static 'js/bootstrap.min.js' %}"></script>


  </body>
</html>

photo/templates/photo/template.html
{% load static %}

<html>

<head>
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
  <title>label me</title>
  <link rel="stylesheet" href="{% static 'css/update.css' %}">
  <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>
<style>
  * {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
  }

  .submit {
    background-color: white;
    /*border: none;*/
    color: black;
    padding: 2vmin 2.5vmin;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 2.5vmin;
  }

  .questions {
    background-repeat: no-repeat;
    background-size: auto;
    border: 3px solid #010801;
    border-radius: 3px;
    box-shadow: 0 0 2px 1px #9a9182;
    background-color: #0071b9;
    background-repeat: repeat;
    background-attachment: scroll;
    background-clip: border-box;
    background-size: cover;
    object-fit: contain;
    max-width: 85%;
    margin-left: 7.5%;
    margin-top: 2%;
    margin-bottom: 2%;
    padding-bottom: 2vmin;
    text-align: center;
    color: #010801;
    font-weight: bold;
    font-size: 2vmin;
  }

  .questions .title {
    font-size: 3vmax;
    color: white;
  }

  .questions p {
    font-size: 2vmax;
    margin-top: 1%;
  }

  .questions input {
    margin-top: 1%;
  }

  .container-fluid {
    width: 100%;
    border: 2px solid black;
    display: grid;
    height: 100%;
  }

  .left {
    display: flex;
    flex-direction: column;
    background-color: #caced1;
    background-clip: border-box;
    background-size: 100% 100%;
    text-align: center;
    justify-content: flex-start;
    padding-top: 3vh;
  }

  .image {
    max-width: 90%;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
  }

  .image img {
    width: 90%;
    object-fit: contain;
    border: 1px solid rgb(136, 125, 125);
    border-radius: 5px;
    box-shadow: 0 0 1px 1px rgba(0, 140, 186, 0.5);
    margin-left: 5%;
  }

  .image .main_img {
    border: none;
    box-shadow: none;
    /*border-radius: 5px;*/
    max-height: 75vh;
    margin-left: 10%;
  }

  #customers {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    align-items: center;
    width: 98%;
    margin-top: 1vh;
    margin-left: auto;
    margin-right: auto;
  }

  #customers td,
  #customers th {
    height: 3vh;
    /*width: 100%;*/
    border: 1px solid rgb(20, 2, 2);
    padding: 2vh;
  }

  #customers td,
  #customers th {
    height: 3vh;
    border: 1px solid rgb(20, 2, 2);
    padding: 2vh;
  }

  /*
    #customers th:nth-child(1){width: 100%;}
    #customers th:nth-child(2){width: 100%;}
    #customers th:nth-child(3){width: 100%;}
    #customers th:nth-child(4){width: 100%;}
    */

  #customers tr:nth-child(1) { background-color: #a0a0a0; }
  #customers tr:nth-child(2) { background-color: #c5c5c5; }
  #customers tr:nth-child(3) { background-color: #c5c5c5; }
  #customers tr:nth-child(4) { background-color: #c5c5c5; }

  /*#customers tr:nth-child(even){background-color: #a39f9f;}
    #customers tr:nth-child(odd){background-color: #747171;}*/
  #customers tr:hover:nth-child(1) {
    background-color: #a0a0a0;
  }

  /*rgba(44, 44, 44, 0.534);}*/
  #customers tr:hover {
    background-color: #cccccc;
    ;
  }

  #customers th {
    padding-top: 4vh;
    padding-bottom: 800vh;
    text-align: left;
    background-color: #4CAF50;
    color: rgb(236, 14, 14);
  }

  meter {
    margin-top:1vmax;
    width:100%; 
    height: 15px;
    box-shadow: 0 5px 5px -5px #999 inset;
    background-color: whiteSmoke;
    /*
    background-image: linear-gradient(
      90deg, 
      #8bcf69 5%, 
      #e6d450 5%,
      #e6d450 15%,
      #f28f68 15%,
      #f28f68 55%,
      #cf82bf 55%,
      #cf82bf 95%,
      #719fd1 95%,
      #719fd1 100%
    );*/
    background-size: 100% 100%;
  }

  .loader {
    border: 16px solid #f3f3f3; /* Light grey */
    border-top: 16px solid #3498db; /* Blue */
    border-radius: 50%;
    width: 240px;
    height: 240px;
    animation: spin 2s linear infinite;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
</style>

<body>
  <div class="container-fluid">
    <div class="left">
      <div style="
      overflow-x:auto;
      margin-top:5px;
      color: white; 
      padding-bottom: 0px;
      font-size:2.5vmin;
      font-family: Arial, Helvetica, sans-serif;" class="questions">
        <p>İlerleme Durumu: {{ survey.count|add:"1" }} / 30</p>
        <!--<progress id="file" value="32" max="100"> 32% </progress>-->
        <meter id="survey_progress", min="0", max="30", value="{{ survey.count|add:'1' }}"></meter>
      </div>
      
      {% if photo.img %} 
      <div class="image">
        <img src="{{ photo.img.url }}" class="main_img">
        <div id="loading_screen" hidden style="
          width:100%;
          height:120%;
          margin-left:10%;
          position: fixed; 
          background-color:rgba(73, 73, 73, 0.479)">
          <div class="loader" style="
            margin-left:auto;
            margin-right:auto;
            margin-top:25%;"></div> 
        </div>
      </div>
      {% endif %}
      
      
      <div style="overflow-x:auto;" class="questions">
        <form method="Post"> {% csrf_token %}
          <table id="customers">
            <tbody>
              <tr style="text-align:center;font-size:1.7vmin;">
                <td width="60%"> </td>
                <td width="8%" ><b>%0<br>(çok kötü)<br><i>(very bad)</i></b></td>
                <td width="8%"><b>%25<br>(kötü)<br><i>(bad)</i></b></td>
                <td width="8%"><b>%50<br>(orta)<br><i>(average)</i></b></td>
                <td width="8%"><b>%75<br>(iyi)<br><i>(good)</i></b></td>
                <td width="8%"><b>%100<br>(çok iyi)<br><i>(very good)</i></b></td>
              </tr>

              <tr style="text-align:center">
                <td style="text-align:left">
                  <strong style="font-size:2vmin;" for="id_answer1">Bu resim göze ne kadar hoş görünüyor?<br><i>How pleasing to the eye does this picture look?</i></strong>
                </td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="0" id="id_answer1" name="answer1" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="25" id="id_answer1" name="answer1" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="50" id="id_answer1" name="answer1" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="75" id="id_answer1" name="answer1" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="100" id="id_answer1" name="answer1" required></td>
              </tr>

              <tr style="text-align:center">
                <td style="text-align:left">
                  <strong style="font-size:2vmin;" for="id_answer2">Bu resmin görüntü kalitesi (ışık, netlik, vs.) nasıldır?<br><i>How is the image quality (light, clarity, etc.) of this picture?</i></strong>
                </td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="0" id="id_answer2" name="answer2" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="25" id="id_answer2" name="answer2" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="50" id="id_answer2" name="answer2" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="75" id="id_answer2" name="answer2" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="100" id="id_answer2" name="answer2" required></td>
              </tr>

              <tr style="text-align:center">
                <td style="text-align:left">
                  <strong style="font-size:2vmin;" for="id_answer3">Bu resim sizce evin görünen bölümü (oda, mutfak vs.)
                    hakkında ne kadar bilgi veriyor? <br> (planı, kullanılan malzemele tipi ve özellikleri, vs.)<br><i>How much information do you think this picture gives about the visible part of the house (room, kitchen, etc.)?<br>(plan, type and properties of materials used, etc.)</i></strong>
                </td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="0" id="id_answer3" name="answer3" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="25" id="id_answer3" name="answer3" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="50" id="id_answer3" name="answer3" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="75" id="id_answer3" name="answer3" required></td>
                <td onclick="this.children[0].checked=true"><input type="RADIO" value="100" id="id_answer3" name="answer3" required></td>
              </tr>

            </tbody>
          </table>

          <!--<button type="button" class="submit" onclick="javascript:history.go(-1)">Geri</button>-->
          <input id="submit_button" class="submit" onsubmit="document.getElementById('loading_screen').hidden=false" type="submit" value="Sıradaki (Next)">
        </form>
      </div>
    </div>
  </div>


  <script src="{% static 'js/bootstrap.min.js' %}"></script>


  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#blah')
            .attr('src', e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
      }
    }
  </script>
</body>

</html>